export const LOGIN_POST_ERROR = "LOGIN_POST_ERROR";
export const USER_GET_ERROR = "USER_GET_ERROR";
export const GOOGLELOGIN_POST_ERROR = "GOOGLELOGIN_POST_ERROR";
export const REGISTRATION_POST_ERROR = "REGISTRATION_POST_ERROR";
export const MARKER_POST_ERROR = "MARKER_POST_ERROR";